### PR TITLE
Fix delegated votes off by one

### LINKED ISSUE #101: Count of delegated votes off by one
The results pages are reporting 1 delegated vote, at least for the consultation `demo1` from `icademo`. None of the 5 participants performed such vote.

Screenshot from 2021-04-28 12-56-43

It might be that the SQL query is returning a result when the result set should be empty.

### PR DESCRIPTION
**Pull request by sauloperez**
Closes #101 . You can read the details on the issue but the problem was that we were returning a delegation just because it matched a vote's author even though its setting and thus consultation didn't match the vote's consultation.

What I did here is to make `ConsultationDelegations` stick to its meaning and return all delegations that belong to the passed consultation. That led to creating a new query object `GranteeDelegations` that replaced former calls to said query. This enabled us to reuse `ConsultationDelegations` in `DelegatesVotesByConsultation` and `DelegatesVotesByQuestion`. The two queries that were buggy.

While doing this, I tried to establish an AR association between `Consultation::Vote` and `Delegation` to ease querying but I didn't succeed. I had to fall back to the `DelegationVotes` query object.

I also realized (I think I've seen before) that this `DelegatesVotesByQuestion` is causing an N+1. We're using for each individual question while it should return a Hash-like with a count per question but that's a separate issue that would make this too large.

The rest is just renaming, tiny improvements and additional specs which reproduced the issue.

### CODE REVIEW

File: app/queries/decidim/action_delegator/delegation_votes.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+    # This query object replaces the ActiveRecord association we would have between the Vote and
+    # Delegation models. Unfortunately we can't use custom foreign keys on both ends of the
+    # association.
+    class DelegationVotes < Rectify::Query
+      def query
+        Delegation
+          .joins(<<-SQL)
+            INNER JOIN decidim_consultations_votes
+              ON decidim_consultations_votes.decidim_author_id =
+                decidim_action_delegator_delegations.granter_id
```
Comment (sauloperez) [inline app/queries/decidim/action_delegator/delegation_votes.rb:14]: Arelize

File: app/queries/decidim/action_delegator/delegates_votes.rb [hunk 2]
```diff
@@ -4,9 +4,17 @@ module Decidim
   module ActionDelegator
     class DelegatesVotes < Rectify::Query
```
Comment (sauloperez) [inline app/queries/decidim/action_delegator/delegates_votes.rb:5]: We can replace this one with `DelegationVotes` but it may be a good idea to rename it instead so it doesn't get lost in the Git history.

File: app/queries/decidim/action_delegator/consultation_delegations.rb [hunk 3]
```diff
@@ -3,11 +3,11 @@
 module Decidim
   module ActionDelegator
     class ConsultationDelegations < Rectify::Query
-      def self.for(consultation, user)
+      def self.for(consultation, user = nil)
         new(consultation, user).query
       end
 
-      def initialize(consultation, user)
+      def initialize(consultation, user = nil)
```
Comment (sauloperez) [inline app/queries/decidim/action_delegator/consultation_delegations.rb:10]: we can remove `user` altogether.

File: app/queries/decidim/action_delegator/delegates_votes_by_consultation.rb [hunk 4]
```diff
@@ -3,26 +3,21 @@
...
-      def consultation_votes
-        Decidim::Consultations::Vote
-          .joins("INNER JOIN decidim_consultations_questions
-                    ON decidim_consultations_votes.decidim_consultation_question_id = decidim_consultations_questions.id
-                  INNER JOIN decidim_consultations
-                    ON decidim_consultations.id = decidim_consultations_questions.decidim_consultation_id")
-          .where(decidim_consultations: { id: consultation.id })
+      def consultation_delegated_votes
+        ConsultationDelegations.for(consultation)
+          .merge(DelegationVotes.new.query)
```
Comment (sauloperez) [inline app/queries/decidim/action_delegator/delegates_votes_by_consultation.rb:20]: We can now get back to using `relation` so the changeset is smaller.
